[store]
[store.primary]
connection = "postgresql://${postgres_user}:${postgres_pass}@${postgres_host}/${postgres_db}"
pool_size = 30


[chains]
ingestor = "graph_indexed_node_common"

[chains.mainnet]
shard = "primary"
provider = [
    { label = "mainnet-0", url = "http://165.227.131.112:8545", features = ["archive", "traces"] }
]

[general]
query = "graph_query_node"

[deployment]
[[deployment.rule]]
match = { network = "mainnet" }
indexers = ["graph_indexed_node_mainnet"]

[[deployment.rule]]
indexers = ["graph_indexed_node_common"]
